"""empty message

Revision ID: b5a882d54f07
Revises: 5310147e3d68
Create Date: 2022-08-28 19:08:15.642696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a882d54f07'
down_revision = '5310147e3d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cartItems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartItems',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"cartItems_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name='cartItems_cart_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='cartItems_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cartItems_pkey')
    )
    op.drop_table('cartitems')
    # ### end Alembic commands ###
